### ISSUE TITLE
Drivers should handle Acrobat's broken transparency

### ISSUE THREAD

**Issue by hmenke** [latex3/graphics-def#16]
For pdfTeX:
```latex
\pdfpageattr{/Group <</S /Transparency /I true /CS /DeviceRGB>>}
```
For XeTeX:
```latex
\special{pdf: put @thispage <</Group << /S /Transparency /I true /CS /DeviceRGB>> >>}
```
For LuaTeX:
```latex
\pdfvariable pageattr{/Group <</S /Transparency /I true /CS /DeviceRGB>>}
```

I would submit a PR put I don't know exactly where those instructions should go in the driver files.

**Comment by davidcarlisle** [comment]
Yes I saw tex.sx discussion on this as well.

Is there a reference to exactly what the issue is, I particularly wonder
about referencing DeviceRGB unconditionally rather than any other colour
model, is this always required or are there potential downsides. Without
understanding the pdf issue better I can't really say if

the graphics driver should always do this or

it should have an option (possibly on by default) to do this  or

it should be handled by packages that are setting up transparency (eg tikz)
once they know exactly what transparency mechanisms they are setting up.

**Comment by hmenke** [comment]
Sorry, but the driver has to handle it.  Otherwise included graphics containing transparencies break.  See the linked questions on TeX.SX.  As to whether `DeviceRGB` is special or even required, I have no idea.

**Comment by josephwright** [comment]
I'm not sure it's as simple as that. First, this seems to be a bug in Adobe Reader (or the PDF spec?), which one could argue is 'not our fault' and should simply be reported to Adobe. Assuming one wants a fix at the TeX end (not in say preflight), then there is the entire 'will it get fixed' and 'will multiple calls cause problems question. For LaTeX one can reasonably hope to track packages, but the graphics drivers also work in plain, and there that is not the case. For example, what happens if the user also has the 'fix' line in their document? As @davidcarlisle  says, there is also the entire question of other arrangements for colour ...

**Comment by hmenke** [comment]
@josephwright Quoting from the Adobe forum (https://forums.adobe.com/message/3108003#3108003)

>It's an aspect of the implementation of the PDF standard in Acrobat concerning the choice of default "transparency blending space" when a producer doesn't include an explicit one in the PDF.
> 
> The way to correct it is for the PDF producer to ensure that when all content on the page is in RGB, that an RGB-based blending space be specified in the page's transparency group.
> 
> I believe that the current version of PdfTeX do the right thing - but this file was produced with an older version.

The last statement is obviously not true but this also puts the burden on LaTeX to produce the correct thing.

**Comment by josephwright** [comment]
@hmenke Thanks for the reference: useful for understanding the issue.

The wrinkle in what the Adobe staff say is the 'when all content on the page is in RGB' bit: I wonder what happens (or is supposed to happen) when that's not true. 

One might argue that this should be solved at the engine level: they are in a position to add arbitrary data to the PDF/intermediate output anyway. However, I suppose the issue of timing comes up: the engine doesn't even know that an image will be included when a page starts.

I suspect we are unlikely to get work done at the same time on all engines (don't forget (u)pTeX!), so this may well need to be fixed at the macro level. The question then is as @davidcarlisle says whether one gives a way 'out'. (I also have to think about covering the same thing in the `expl3` drivers, but they are easier in some ways.)

**Comment by davidcarlisle** [comment]
My main concern is


The way to correct it is for the PDF producer to ensure that when all
content on the page is in RGB, that an RGB-based blending space be
specified in the page's transparency group.


the graphics driver certainly does not know that all the page content is
RGB, the document may be specifying CMYK (or any other) colour) so it is
really not clear that it should be doing this by default. It could perhaps
provide an option or command that makes it easy to do this rather than the
user needing to know the arcane literal pdf to inject.

**Comment by davidcarlisle** [comment]
Just for reference, how another pdf generator is handling this


https://github.com/empira/PDFsharp/blob/master/src/PdfSharp/Pdf/PdfPage.cs#L589


note it is not unconditionally setting RGB, it's is conditionally setting this to RGB or CMYK or skipping it.

(I don't know this tool, I was just looking for things generating this setting)

**Comment by hmenke** [comment]
ConTeXt does the correct thing using some Lua magic in the backend.  See [`lpdf-col.lua`](https://github.com/contextgarden/context-mirror/blob/beta/tex/context/base/mkiv/lpdf-col.lua) (Ctrl+F `getpagecolormodel`)

**Comment by manuel-kuehner** [comment]
Hello all together,
thanks for working on the problem!

My post on https://tex.stackexchange.com somehow got a lot of unexpected negative attention. I did not mean to be mean at all :).

I do not have the skill to work with you on the problem but I appreciate it very much (if that means anything).

Manuel

PS: I copied the the relevant part from @hmenke 's link:

```
% ---
local getpagecolormodel       = colors.getpagecolormodel
% ---
local function addpagegroup()
    local model = getpagecolormodel()
    if model then
        local g = transparencygroups[model]
        if g then
            addtopageattributes("Group",g)
        end
    end
end
% ---
statistics.register("page group warning", function()
    if done then
        local model = getpagecolormodel()
        if model and not transparencygroups[model] then
            return "transparencies are used but no pagecolormodel is set"
        end
    end
end)
```

PPS: I copied the the relevant part from @davidcarlisle 's link:

```
#if true
            // Add transparency group to prevent rendering problems of Adobe viewer.
            // Update (PDFsharp 1.50 beta 3): Add transparency group only of ColorMode is defined.
            // Rgb is the default for the ColorMode, but if user sets it to Undefined then
            // we respect this and skip the transparency group.
            TransparencyUsed = true; // TODO: check XObjects
            if (TransparencyUsed && !Elements.ContainsKey(Keys.Group) &&
                _document.Options.ColorMode != PdfColorMode.Undefined)
            {
                PdfDictionary group = new PdfDictionary();
                _elements["/Group"] = group;
                if (_document.Options.ColorMode != PdfColorMode.Cmyk)
                    group.Elements.SetName("/CS", "/DeviceRGB");
                else
                    group.Elements.SetName("/CS", "/DeviceCMYK");
                group.Elements.SetName("/S", "/Transparency");
                //False is default: group.Elements["/I"] = new PdfBoolean(false);
                //False is default: group.Elements["/K"] = new PdfBoolean(false);
            }
#endif
```

**Comment by hmenke** [comment]
There hasn't been any activity here for two weeks, so I guess I just suggest what I was thinking.

In ConTeXt the user can set the page color model via the macro interface `\setpagecolormodel`.  If the user set this color model, it will be added to the PDF on shipout.  The page color model can of course be adjusted per page.

LaTeX could perform something similar which would also be backwards compatible where the page color model could be chosen as an option to the `color` package.  If it is set at shipout, add it to the PDF, otherwise do nothing.  I suppose the appropriate place would be `\GPT@pageliteral`.

**Comment by u-fischer** [comment]
According to the updates in https://tex.stackexchange.com/questions/417485/transparency-and-pdf-wrong-colors-bug-feature-request the problem has been resolved by the newest adobe pdf-viewer, and on my OS I can't reproduce the problem. Do we still need an option to set the page color model or can we close this as resolved externally?

**Comment by davidcarlisle** [comment]
The issue appears resolved with current adobe reader (and acrobat pro) so closing here.

**Comment by hmenke** [comment]
The current Adobe Reader on Linux is 9.5.5 where this is not fixed.

**Comment by davidcarlisle** [comment]
@hmenke  isn't it more true to say that acrobat isn't supported on linux and the last one released happens to be 9.5.5 and no bugs in it will be fixed, I think pdf generators can't commit to supporting that otherwise no new features like tagging or pdf 2.0 or anything will be added ever.  As far as I understand the discussion above it isn't clear that something can easily be added to support old acrobat that won't have a detrimental effect in some conforming pdf readers. Something has to give somewhere...
